services:
  nginx:
    image: nginx:latest
    ports:
      - "9001:9001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    entrypoint: sh -c "sleep 10 && nginx -g 'daemon off;'"

  backend:
    build: .
    ports:
      - "9002-9004:9002-9004"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chat-app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet

volumes:
  mongo-data: