export enum UserErrorCodes {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  INVALID_USERNAME = 'INVALID_USERNAME',
  INVALID_NAME = 'INVALID_NAME',
  UPDATE_FAILED = 'UPDATE_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
}
